### ISSUE TITLE
Broken link to poster

### ISSUE THREAD

**Issue by jmloyola** [mndominguez/mlss2018#4]
Hello @mndominguez,
One [commit](https://github.com/mndominguez/mlss2018/commit/33fe4db2a3edb3b1663046dde409ac246f55bcb7) from last week broke the link to my poster. The name of the file was modified from `juan_martin_loyola.pdf` to `Juan_Martin_Loyola.pdf`
Do you want me to change it myself?

**Comment by mndominguez** [comment]
Hey, sorry about that. I just fixed it. Thanks for letting me know.
